store/urls.py
from django.urls import path

from .views import ItemDetail, BuyItem, PayForGoods, success_payment

app_name = 'store'

urlpatterns = [
    path('item/<int:pk>', ItemDetail.as_view(), name='item-detail'),
    path('buy/<int:pk>', BuyItem.as_view(), name='buy-item'),
    path('pay_for_goods', PayForGoods.as_view(), name='pay-for-goods'),
    path('success_payment', success_payment, name='success-payment'),
]

stripe_store/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

store/models.py
from django.db import models
from django.urls import reverse

LTE = 'LTE'
LT = 'LT'
GTE = 'GTE'
GT = 'GT'
EQ = 'EQ'
PRICE_CONDITION_CHOICES = [
    (LTE, '<='),
    (LT, '<'),
    (GTE, '>='),
    (GT, '>'),
    (EQ, '='),
]


class Item(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, verbose_name='Название')
    description = models.TextField(null=False, blank=True, verbose_name='Описание')
    price = models.PositiveIntegerField(null=False, blank=False, verbose_name='Цена')

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('store:buy-item', args=[self.id])

    class Meta:
        verbose_name = 'Вещь'
        verbose_name_plural = 'Вещи'


class Order(models.Model):
    items = models.ManyToManyField(Item, related_name='orders', verbose_name='Вещи')

    def __str__(self):
        return 'order ' + str(self.id)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class Tax(models.Model):
    DELIVERY = 'DV'
    ADDITIONAL_COST = 'AC'
    TAXES_CHOICES = [
        (DELIVERY, 'Доставка'),
        (ADDITIONAL_COST, 'НДС')
    ]
    orders = models.ManyToManyField(Order, related_name='taxes', blank=True, verbose_name='Заказы')
    price = models.PositiveIntegerField(verbose_name='Цена')
    percentage_price = models.BooleanField(default=False, verbose_name='Цена налога указана в процентах')
    condition_price = models.PositiveIntegerField(verbose_name='Цена для условия')
    keyword = models.CharField(max_length=3, choices=TAXES_CHOICES, verbose_name='Вид налога')
    order_price_condition = models.CharField(
        verbose_name='Оператор условия',
        help_text='Условный оператор, который должен выполниться, для использования этого налога, например,'
                  ' если в этом поле указан знак ">", то если "цена заказа" > "цена налога", то налог активируется'
                  ' относительно данного заказа', max_length=3,
        choices=PRICE_CONDITION_CHOICES)

    def __str__(self):
        return self.keyword + ' ' + str(self.price)

    class Meta:
        verbose_name = 'Налог'
        verbose_name_plural = 'Налоги'


class Discount(models.Model):
    MIDDLE_ORDER = 'MO'
    BIG_ORDER = 'BO'
    DISCOUNT_CHOICES = [
        (MIDDLE_ORDER, 'Средний заказ'),
        (BIG_ORDER, 'Большой заказ')
    ]
    orders = models.ManyToManyField(Order, related_name='discounts', blank=True, verbose_name='Заказы')
    price = models.PositiveIntegerField(verbose_name='Цена')
    percentage_price = models.BooleanField(default=False, verbose_name='Цена скидки указана в процентах')
    condition_price = models.PositiveIntegerField(verbose_name='Цена для условия')
    keyword = models.CharField(max_length=3, choices=DISCOUNT_CHOICES, verbose_name='Вид налога')
    order_price_condition = models.CharField(
        verbose_name='Оператора условия',
        help_text='Условный оператор, который должен выполниться, для использования этой скидки, например,'
                  ' если в этом поле указан знак ">", то если "цена заказа" > "цена скидки", то скидка активируется'
                  ' относительно данного заказа', max_length=3, choices=PRICE_CONDITION_CHOICES)

    def __str__(self):
        return self.keyword + ' ' + str(self.price)

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'

store/views.py
from django.db.models import Sum, F
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
import stripe

from store.models import Item, Order, Tax, Discount
from stripe_store.settings import STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY


class ItemDetail(View):
    """

    Отображает информацию о товаре

    """
    template_name = 'store/item_detail.html'

    def get(self, request, pk):
        item = get_object_or_404(Item, pk=pk)
        is_item_in_order = False
        order = request.session.get('order_id', False)
        if order:
            is_item_in_order = Order.objects.filter(id=order, items=item).exists()
        args = {'item': item,
                'pub_key': STRIPE_PUBLISHABLE_KEY,
                'is_item_in_order': is_item_in_order}
        return render(request, self.template_name, args)


class BuyItem(View):
    """

    Добавляет/удаляет товар из текущего заказа пользователя

    """

    def post(self, request, pk):
        item = get_object_or_404(Item, pk=pk)
        if request.session.get('order_id', False):
            order = Order.objects.get(id=request.session['order_id'])
        else:
            order = Order.objects.create()
            request.session['order_id'] = order.id
        order.items.add(item)
        return HttpResponse()

    def delete(self, request, pk):
        item = get_object_or_404(Item, pk=pk)
        order = Order.objects.get(id=request.session['order_id'])
        order.items.remove(item)
        return HttpResponse()


class PayForGoods(View):
    """

    Осуществляется оплата заказа с учетом всех скидок и налогов

    """
    template_name = 'store/checkout.html'

    def post(self, request):
        stripe.api_key = STRIPE_SECRET_KEY
        order = request.session.get('order_id', False)
        if order:
            order = Order.objects.filter(id=order).annotate(
                total_price=Sum('items__price'),
            ).get()
            total_price_change, total_percentage_price_change = toggle_taxes_and_discounts(order)
            amount = int(order.total_price + total_price_change +
                         (order.total_price * total_percentage_price_change) / 100) * 100
            if 'payment_intent_id' not in request.session:
                intent = stripe.PaymentIntent.create(
                    amount=amount,
                    currency='rub',
                    payment_method_types=['card']
                )
                request.session['payment_intent_id'] = intent.id
            else:
                intent = stripe.PaymentIntent.modify(
                    request.session['payment_intent_id'],
                    amount=amount,
                )
            args = {
                'secret_key': intent.client_secret,
                'pub_key': STRIPE_PUBLISHABLE_KEY,
                'payment_intent_id': intent.id,
                'amount': int(amount / 100),
                'currency': '₽'
            }
            return render(request, self.template_name, args)
        else:
            return HttpResponse('Корзина пуста')


def success_payment(request):
    """

    Подтверждается оплата товара и показывается страница с сообщением об успехе операции
    :param request: обычный post запрос(в случае get запроса будет произведен redirect на страницу первого товара)
    :return: страница с сообщением об успешной покупке
    """
    if request.method == 'POST':
        payment_intent_id = request.POST['payment_intent_id']
        payment_method_id = request.POST['payment_method_id']

        stripe.api_key = STRIPE_SECRET_KEY
        stripe.PaymentIntent.modify(
            payment_intent_id,
            payment_method=payment_method_id
        )
        stripe.PaymentIntent.confirm(payment_intent_id)

        order = Order.objects.get(id=request.session.get('order_id', False))
        order.delete()
        request.session.flush()
        return render(request, 'store/success_payment.html')
    else:
        return redirect('store:item-detail', pk=1)


def toggle_taxes_and_discounts(order):
    """

    Добавляет к выбранному заказу все скидки и налоги условиям которых он удовлетворяет

    :param order: выбранный заказ
    :return: изменение цены в текущей валюте и изменение цены в процентах от нее
    """
    # удаляем все уже имеющиеся скидки и налоги
    order.taxes.clear()
    order.discounts.clear()
    # берем все существующие скидки и налоги
    taxes = Tax.objects.all()
    discounts = Discount.objects.all()

    total_price_change = 0
    total_percentage_price_change = 0
    # подсчитываем изменение цены из-за налогов
    order, price_change, percentage_price_change = check_conditions(order, taxes, 'taxes')
    total_price_change += price_change
    total_percentage_price_change += percentage_price_change
    # подсчитываем изменение цены из-за скидов
    order, price_change, percentage_price_change = check_conditions(order, discounts, 'discounts')
    total_price_change += price_change
    total_percentage_price_change += percentage_price_change
    # сохраняем имеющийся заказ с добавленными скидками, налогами и изменениями цены
    order.save()
    return total_price_change, total_percentage_price_change


def check_conditions(order, queryset, query_type):
    """

    Подсчитываем изменение цены заказа для данного order и всех налогов/скидок в queryset
    :param order: текущий заказ пользователя
    :param queryset: queryset скидок или налогов
    :param query_type: "discount" или "tax" в зависимости от того скидка это или налог
    :return: текущий заказ, изменение цены в единицах текущей валюты, изменение цены в процентах от нее
    """
    price_change = 0
    percentage_price_change = 0
    for item in queryset:
        if item.order_price_condition == 'LTE':
            if order.total_price <= item.condition_price:
                if item.percentage_price:
                    percentage_price_change = change_price(query_type, percentage_price_change, item, order)
                else:
                    price_change = change_price(query_type, price_change, item, order)

        elif item.order_price_condition == 'LT':
            if order.total_price < item.condition_price:
                if item.percentage_price:
                    percentage_price_change = change_price(query_type, percentage_price_change, item, order)
                else:
                    price_change = change_price(query_type, price_change, item, order)

        elif item.order_price_condition == 'GT':
            if order.total_price > item.condition_price:
                if item.percentage_price:
                    percentage_price_change = change_price(query_type, percentage_price_change, item, order)
                else:
                    price_change = change_price(query_type, price_change, item, order)

        elif item.order_price_condition == 'GTE':
            if order.total_price >= item.condition_price:
                if item.percentage_price:
                    percentage_price_change = change_price(query_type, percentage_price_change, item, order)
                else:
                    price_change = change_price(query_type, price_change, item, order)

        elif item.order_price_condition == 'EQ':
            if order.total_price == item.condition_price:
                if item.percentage_price:
                    percentage_price_change = change_price(query_type, percentage_price_change, item, order)
                else:
                    price_change = change_price(query_type, price_change, item, order)
    return order, price_change, percentage_price_change


def change_price(query_type, price_change, item, order):
    """

    Непосредственно производим расчеты для данного налога/скидки

    :param query_type: "discount" или "tax" в зависимости от того скидка это или налог
    :param price_change: измеющееся на данный момент изменение цены
    :param item: текущий налог или скидка
    :param order: текущий заказ
    :return: новое изменение цены
    """
    if query_type == 'discounts':
        price_change -= item.price
        order.discounts.add(item)
    else:
        price_change += item.price
        order.taxes.add(item)
    return price_change

templates/store/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Оплата</title>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
{% load humanize %}
<p>С учетом скидок и налогов ваш заказ вышел на стоимость: {{ amount|intcomma }} {{ currency }}</p>
<form action="{% url 'store:success-payment' %}" method="post" id="payment-form">
    {% csrf_token %}
    <div id="card-element">

    </div>
    <div id="card-errors" role="alert">

    </div>
    <input type="hidden" name="payment_intent_id" value="{{ payment_intent_id }}">
    <input id="payment_method_id" type="hidden" name="payment_method_id" value="{{ payment_intent_id }}">
    <button id="submit-button">Заплатить</button>
</form>
</body>
<script>
    $(window).on('load', function () {
        let stripe = Stripe('{{ pub_key }}');
        let elements = stripe.elements()
        let style = {
            base: {
                color: '#32325d'
            },
            invalid: {
                color: '#fa755a'
            }
        };
        let card = elements.create('card', {'style': style});
        card.mount("#card-element");
        card.on('change', function (event) {
            let displayError = $('#card-errors');
            if (event.error) {
                displayError.text(event.error.message);
            } else {
                displayError.text('');
            }
        })
        let form = $('#payment-form');
        form.on('submit', function (event) {
            event.preventDefault();
            stripe.createToken(card).then(function (result) {
                if (result.error) {
                    let errorElement = $('#card-errors');
                    errorElement.text(result.error.message);
                } else {
                    stripe.createPaymentMethod({
                        type: 'card',
                        card: card
                    }).then(function (result) {
                        if (result.error) {
                            let errorElement = $('#card-errors');
                            errorElement.text(result.error.message);
                        } else {
                            let form = $('#payment-form').get(0);
                            let hiddenInput = $('#payment_method_id');
                            hiddenInput.val(result.paymentMethod.id);
                            form.submit();
                        }
                    })
                }
            })
        })
    })
</script>
</html>

templates/store/item_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ item.name }}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
<h1>{{ item.name }}</h1>
<p>{{ item.description }}</p>
<p>{{ item.price }} ₽</p>
<button id="add-to-cart">{% if is_item_in_order %}Убрать из корзины{% else %}Добавить в корзину{% endif %}</button>
<form method="POST" action="{% url 'store:pay-for-goods' %}">
    {% csrf_token %}
    <button type="submit" id="end-buying">Перейти к оплате</button>
</form>
<script>
    let stripe = Stripe('{{ pub_key }}');
    let addToCartItem = $('#add-to-cart');
    addToCartItem.on('click', function () {
        let is_item_in_order = !(addToCartItem.text() === 'Добавить в корзину');
        let item_pk = parseInt('{{ item.id }}');
        $.ajax({
            url: '{{ item.get_absolute_url }}',
            type: (is_item_in_order ? "DELETE" : "POST"),
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            },
            success: function (response) {
                if (!is_item_in_order) {
                    addToCartItem.text('Убрать из корзины')
                } else {
                    addToCartItem.text('Добавить в корзину')
                }
            },
            error: function (data, errors) {
                console.log(data);
                console.log(errors);
            }
        })
    })
</script>

</body>
</html>

templates/store/success_payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Спасибо за покупку!</title>
</head>
<body>
<h1>Спасибо за покупку!</h1>
</body>
</html>